# Generated by Django 5.1 on 2024-08-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
